### ISSUE TITLE
Solve transmit not working from receive mode

### ISSUE THREAD

**Issue by Paladinking** [LiU-SeeGoals/basestation#5]
In order to keep track of connected robots, the basestation listens is in RX mode and receives ids from robots at startup.
To send, it first enters standby1 mode, then transmits, then returns to RX mode. This does not work. Never entering RX mode makes it work again.

**Comment by r0x57n** [comment]
@Paladinking 
Fixed in these branches:
https://github.com/LiU-SeeGoals/robot/tree/motor-ctrl
https://github.com/LiU-SeeGoals/basestation/tree/robot-connect

There were multiple problems, but it kinda boiled down to that PRIM_RX wasn't being set to 0 when we went from RX mode to Standby-I, so when we tried to transmit we went back into RX mode instead.
